name: generate-strings
run-name: generate-strings
on: 
  push:
  schedule:
    - cron: '0 22 * * *'  # 北京时间 06:00
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.12
        uses: actions/setup-python@v5

        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate strings
        run: |
          python get_from_paratranz.py ${{ secrets.PARATRANZ_API_TOKEN }}

      - name: Upload strings
        uses: actions/upload-artifact@v4
        with:
          name: strings
          path: build/strings.tsv