name: generate-strings
run-name: generate-strings
env:
  ATLYSS_VERSION: "1.6.0-beta"
  LOCALYSSATION_VERSION: "0.0.3"
on: 
  push:
  schedule:
    - cron: '0 22 * * *'  # 北京时间 06:00
  workflow_call:
    secrets:
      PARATRANZ_API_TOKEN:
        required: true
        description: "Paratranz API Token"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate strings
        run: |
          python get_from_paratranz.py ${{ secrets.PARATRANZ_API_TOKEN }}
  
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy files
        run: |
          mkdir -p "build/Localyssation Patch zh-CN"
          cp localyssationLanguage.json "build/Localyssation Patch zh-CN"

  artifact:
    runs-on: ubuntu-latest
    needs: [build, copy-files]
    steps:
      - uses: actions/checkout@v4
      - name: Upload strings
        uses: actions/upload-artifact@v4
        with:
          name: Atlyss-${{ env.ATLYSS_VERSION }}_Localyssation-${{ env.LOCALYSSATION_VERSION }}_zh-CN
          path: build/*